### ISSUE TITLE
Download data

### ISSUE THREAD

**Issue by dimasheva1** [usuyama/ePillID-benchmark#5]
I have an issue with downloading data from ePillID Benchmark. Could somebody provide a valid link to download it?

**Comment by jacob-statsig** [comment]
The download is available under the releases page of the Github. (https://github.com/usuyama/ePillID-benchmark/releases/tag/ePillID_data_v1.0). The link in the Readme appears to not be working

**Comment by dimasheva1** [comment]
Thank you!
